
logdir: ../../var/log/
logfile: log
#logfile: edgecomputing
node_logfile: node_log
phantomjs_logfile: phantomjs_log
loglevel: DEBUG
loglevel_to_stdout: WARNING
#rotate_log_size: 268435456 #1024*1024*256B
rotate_log_size: 1073741824 #1024*1024*1024B
#rotate_log_size: 1048576 #1024*1024B
#rotate_log_size: 1000 #1024*1024B
rotate_log_lines: 100000
backup_log_count: 10

pdf_downloading_path: ../../data/edgecomputing/

IEEE_website: "http://ieeexplore.ieee.org"
IEEE_top_page: "http://ieeexplore.ieee.org/Xplore/home.jsp"
IEEE_wait_time_per_download_paper: 60
IEEE_citation_num_at_first_page: 30
IEEE_citation_num_per_more_view: 100
#30, 130, 230, 329, 429, 529, 629, 728, 828, 929
phantomJS_pass: "/usr/local/bin/phantomjs"
myslq_url: "mysql+pymysql://alladmin:admin@localhost/paper_graph?charset=utf8"