
logdir: ../../var/log/
logfile: log
loglevel: DEBUG
rotate_log_size: 268435456 #1024*1024*256B
#rotate_log_size: 1073741824 #1024*1024*1024B
#rotate_log_size: 1048576 #1024*1024B
#rotate_log_size: 1000 #1024*1024B
rotate_log_lines: 100000
backup_log_count: 10

IEEE_top_page: "http://ieeexplore.ieee.org/Xplore/home.jsp"
phantomJS_pass: "/usr/local/bin/phantomjs"
myslq_url: "mysql+pymysql://alladmin:admin@localhost/paper_graph?charset=utf8"